In [79]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error

In [80]:
data = pd.read_csv('diabetesdataset.csv')
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [81]:
x= data.drop(columns=['Outcome'])
x

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47
767,1,93,70,31,0,30.4,0.315,23

In [82]:
y= data['Outcome']
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [83]:
x_train_decision, x_test_decision, y_train_decision, y_test_decision = train_test_split(x,y,test_size=0.2)

In [84]:
x_train_decision

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
689,1,144,82,46,180,46.1,0.335,46
652,5,123,74,40,77,34.1,0.269,28
665,1,112,80,45,132,34.8,0.217,24
594,6,123,72,45,230,33.6,0.733,34
263,3,142,80,15,0,32.4,0.200,63
...,...,...,...,...,...,...,...,...
319,6,194,78,0,0,23.5,0.129,59
42,7,106,92,18,0,22.7,0.235,48
422,0,102,64,46,78,40.6,0.496,21
632,2,111,60,0,0,26.2,0.343,23
320,4,129,60,12,231,27.5,0.527,31

In [85]:

x_test_decision

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
95,6,144,72,27,228,33.9,0.255,40
534,1,77,56,30,56,33.3,1.251,24
333,12,106,80,0,0,23.6,0.137,44
162,0,114,80,34,285,44.2,0.167,27
715,7,187,50,33,392,33.9,0.826,34
...,...,...,...,...,...,...,...,...
183,5,73,60,0,0,26.8,0.268,27
525,3,87,60,18,0,21.8,0.444,21
529,0,111,65,0,0,24.6,0.660,31
350,4,92,80,0,0,42.2,0.237,29
765,5,121,72,23,112,26.2,0.245,30

In [86]:
y_train_decision

689    1
652    0
665    0
594    0
263    0
      ..
319    1
42     0
422    0
632    0
320    0
Name: Outcome, Length: 614, dtype: int64

In [87]:
y_test_decision

95     0
534    0
333    0
162    0
715    1
      ..
183    0
525    0
529    0
350    0
765    0
Name: Outcome, Length: 154, dtype: int64

In [88]:
decision_tree_algorithm= DecisionTreeClassifier()
decision_tree_algorithm.fit(x_train_decision,y_train_decision)

DecisionTreeClassifier()

In [89]:
decision_tree_prediction = decision_tree_algorithm.predict(x_test_decision)
decision_tree_prediction

array([1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [90]:
decision_tree_accuracy= accuracy_score(y_test_decision, decision_tree_prediction)
decision_tree_accuracy

0.7337662337662337

In [91]:
x_train_linear, x_test_linear, y_train_linear, y_test_linear = train_test_split(x,y,test_size=0.2)

In [92]:
x_train_linear

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
619,0,119,0,0,0,32.4,0.141,24
323,13,152,90,33,29,26.8,0.731,43
465,0,124,56,13,105,21.8,0.452,21
55,1,73,50,10,0,23.0,0.248,21
551,3,84,68,30,106,31.9,0.591,25
...,...,...,...,...,...,...,...,...
408,8,197,74,0,0,25.9,1.191,39
144,4,154,62,31,284,32.8,0.237,23
254,12,92,62,7,258,27.6,0.926,44
731,8,120,86,0,0,28.4,0.259,22
241,4,91,70,32,88,33.1,0.446,22

In [93]:
x_test_linear

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
572,3,111,58,31,44,29.5,0.430,22
336,0,117,0,0,0,33.8,0.932,44
300,0,167,0,0,0,32.3,0.839,30
724,1,111,94,0,0,32.8,0.265,45
217,6,125,68,30,120,30.0,0.464,32
...,...,...,...,...,...,...,...,...
214,9,112,82,32,175,34.2,0.260,36
453,2,119,0,0,0,19.6,0.832,72
21,8,99,84,0,0,35.4,0.388,50
686,3,130,64,0,0,23.1,0.314,22
704,4,110,76,20,100,28.4,0.118,27

In [94]:
y_train_linear

619    1
323    1
465    0
55     0
551    0
      ..
408    1
144    0
254    1
731    1
241    0
Name: Outcome, Length: 614, dtype: int64

In [95]:
y_test_linear

572    0
336    0
300    1
724    0
217    0
      ..
214    1
453    0
21     0
686    0
704    0
Name: Outcome, Length: 154, dtype: int64

In [96]:
linear_regression_algorithm= LinearRegression()
linear_regression_algorithm.fit(x_train_linear, y_train_linear)

LinearRegression()

In [97]:
linear_regression_prediction = linear_regression_algorithm.predict(x_test_linear)
linear_regression_prediction

array([ 0.22961888,  0.58134003,  0.7634057 ,  0.23030683,  0.37693967,
        0.64005387,  0.55040481,  0.38993213,  0.54912737,  0.66368365,
        0.47857778,  0.14896985,  0.13493519,  0.07154183,  0.47898505,
        0.41940737,  0.37910806,  0.08576875,  0.83265843,  0.09603098,
        0.58332667,  0.61086772,  0.57382184,  0.20563713,  1.01990598,
        0.09613065,  0.61885516,  0.29273461,  0.70193577,  0.36046263,
        0.48090509,  0.14942739,  0.5181304 ,  0.78247726,  0.44113008,
        0.45381497,  0.17239016,  0.39147555,  0.49402389,  0.05289548,
        0.5658704 , -0.11772991,  0.35339912,  0.03138854,  0.58142789,
        0.33534108,  0.82590751,  0.5835778 ,  0.1405399 ,  0.75193277,
        0.26609162,  0.39310344,  0.38151512,  0.45328399,  0.01537594,
        0.38347021,  0.74738572,  0.33778508,  0.72197915,  0.62287517,
        0.62232877,  0.32384351,  0.68383914, -0.0506889 ,  0.37671446,
       -0.01553815,  1.01926262,  0.19185948,  0.22032001,  0.62414444,
        0.28899733,  0.5635634 ,  0.30344058,  0.3598952 ,  0.14234855,
        0.45223193,  0.20996745,  0.18828932,  0.77924196,  0.10427419,
        0.41183448,  0.12545793,  0.21435042,  0.17624626, -0.03048183,
        0.59241303,  0.47322528,  0.2894342 ,  0.39288338,  0.22114836,
        0.16145961,  0.2123444 ,  0.48871637,  0.40619239,  0.1915552 ,
        0.40214431, -0.00173703,  0.35627911,  0.32031809,  0.12599741,
        0.21444697,  0.14085954,  0.15241888,  0.09731122,  0.57736718,
        0.64468969, -0.0073155 ,  0.11347817,  0.1364075 ,  0.25282343,
        0.48913307,  0.14417422,  0.48047425,  0.65721482,  0.1074043 ,
        0.40303014,  0.37472364,  0.57438379,  0.07979739,  0.25988505,
        0.46167239,  0.6677462 ,  0.27484204,  0.24674562,  0.34354449,
        0.13131983,  0.33523315,  0.12240037,  0.3609134 ,  0.47828342,
        0.23829007,  0.07776966,  0.24299826,  0.44912423,  0.03028948,
        0.13952799,  0.1882403 ,  0.72346883,  0.30846932,  0.142475  ,
        0.21087388,  0.11538094,  0.26009659,  0.60808674,  0.53649618,
        0.21513896,  0.72926142,  0.37468674,  0.51679902,  0.36210191,
        0.52738411,  0.41174755,  0.22790737,  0.1425285 ])

In [98]:
linear_regression_error=mean_squared_error(y_test_linear, linear_regression_prediction)
linear_regression_error

0.16996319972591153

In [99]:
Accuracy_linear = 1 - linear_regression_error
Accuracy_linear

0.8300368002740884